name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - uses: actions/cache@v3
#         with:
#           key: mkdocs-material-${{ github.ref }}
#           path: .cache
#           restore-keys: |
#             mkdocs-material- 

#       - name: Install packages
#         run: pip install mkdocs-material

#       - name: Build Docs
#         run: mkdocs build --site-dir public
      
#       - name: Deploy to GitHub Pages
#         run: mkdocs gh-deploy --force
        # uses: peaceiris/actions-gh-pages@v3
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   publish_dir: ./public

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ github.ref }} 
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
